# Use root/example as user/password credentials
version: "3"

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./web:/www
      - ./docker/webserver/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm-mysql
  php-fpm-mysql:
    build: ./docker/php
    volumes:
      - ./web:/www
    links:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "my-secret-pw"
      MYSQL_USER: "estap"
      MYSQL_PASSWORD: "estap"
      MYSQL_DATABASE: "estap"
    ports:
    - 3306:3306
    volumes:
      - ./database/tmp:/var/lib/mysql
      - ./database/paeda.sql:/docker-entrypoint-initdb.d./paeda.sql